-- Voucher Approval App (HTML/CSS/JS) using Supabase (Postgres + Auth + Storage)
-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text unique,
  full_name text not null,
  role text not null default 'contributor'
    check (role in ('contributor','finance_admin','chairman','super_admin')),
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.vouchers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  date_paid date not null,
  amount_paid numeric(12,2) not null check (amount_paid > 0),
  bank_paid text not null,
  file_path text not null,
  file_name text not null,
  mime_type text not null,
  status text not null default 'submitted'
    check (status in ('submitted','authenticated','approved','rejected')),
  uploaded_at timestamptz not null default now(),
  finance_authenticated_by uuid references public.profiles(id),
  finance_authenticated_at timestamptz,
  chairman_approved_by uuid references public.profiles(id),
  chairman_approved_at timestamptz,
  last_comment text
);

create index if not exists ix_vouchers_status_uploaded on public.vouchers(status, uploaded_at desc);
create index if not exists ix_vouchers_user_uploaded on public.vouchers(user_id, uploaded_at desc);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid references public.profiles(id),
  actor_email text,
  action text not null,
  target_type text,
  target_id text,
  message text,
  metadata jsonb
);

create index if not exists ix_audit_created on public.audit_logs(created_at desc);
create index if not exists ix_audit_action_created on public.audit_logs(action, created_at desc);

create or replace function public.current_role()
returns text
language sql
stable
security definer
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace view public.v_user_summary as
select
  p.id as user_id,
  p.username,
  p.full_name,
  count(v.id) as vouchers_count,
  coalesce(sum(v.amount_paid), 0) as total_amount
from public.profiles p
left join public.vouchers v on v.user_id = p.id
where p.role = 'contributor'
group by p.id, p.username, p.full_name
order by coalesce(sum(v.amount_paid), 0) desc;

alter table public.profiles enable row level security;
alter table public.vouchers enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles read own or staff" on public.profiles;
create policy "profiles read own or staff"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.current_role() in ('finance_admin','chairman','super_admin'));

drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "profiles update own no role change" on public.profiles;
create policy "profiles update own no role change"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid() and role = public.current_role());

drop policy if exists "profiles super admin update" on public.profiles;
create policy "profiles super admin update"
on public.profiles for update
to authenticated
using (public.current_role() = 'super_admin')
with check (public.current_role() = 'super_admin');

drop policy if exists "vouchers insert own" on public.vouchers;
create policy "vouchers insert own"
on public.vouchers for insert
to authenticated
with check (user_id = auth.uid() and public.current_role() = 'contributor');

drop policy if exists "vouchers select own or staff" on public.vouchers;
create policy "vouchers select own or staff"
on public.vouchers for select
to authenticated
using (user_id = auth.uid() or public.current_role() in ('finance_admin','chairman','super_admin'));

drop policy if exists "vouchers finance update submitted" on public.vouchers;
create policy "vouchers finance update submitted"
on public.vouchers for update
to authenticated
using (public.current_role() in ('finance_admin','super_admin') and status = 'submitted')
with check (public.current_role() in ('finance_admin','super_admin'));

drop policy if exists "vouchers chairman update authenticated" on public.vouchers;
create policy "vouchers chairman update authenticated"
on public.vouchers for update
to authenticated
using (public.current_role() in ('chairman','super_admin') and status = 'authenticated')
with check (public.current_role() in ('chairman','super_admin'));

drop policy if exists "audit insert own" on public.audit_logs;
create policy "audit insert own"
on public.audit_logs for insert
to authenticated
with check (actor_id = auth.uid());

drop policy if exists "audit select super admin" on public.audit_logs;
create policy "audit select super admin"
on public.audit_logs for select
to authenticated
using (public.current_role() = 'super_admin');

-- Storage policies (after creating bucket 'vouchers')
drop policy if exists "storage upload own vouchers" on storage.objects;
create policy "storage upload own vouchers"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'vouchers'
  and name like (auth.uid()::text || '/%')
);

drop policy if exists "storage read own or staff" on storage.objects;
create policy "storage read own or staff"
on storage.objects for select
to authenticated
using (
  bucket_id = 'vouchers'
  and (
    name like (auth.uid()::text || '/%')
    or public.current_role() in ('finance_admin','chairman','super_admin')
  )
);
